name: ESLint
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn run eslint . --ext .ts,.tsx
    - name: Run ESLint
      run: eslint . --ext .js,.jsx,.ts,.tsx
